source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'twitter-bootswatch-rails', '~> 3.3.2'
gem 'twitter-bootswatch-rails-helpers'
gem 'therubyracer'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'geocoder', '~> 1.2.7'
gem 'leaflet-rails', '~> 0.7.4'
gem 'font-awesome-rails', '~> 4.3.0.0'
gem 'dragonfly', '~> 1.0.7'
gem 'linkedin', '~> 1.0.0'
gem 'draper', '~> 1.3'
gem 'friendly_id', '~> 5.1.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'bootstrap-sass'
gem 'figaro', '>= 1.0.0.rc1'
gem 'haml-rails'
gem 'high_voltage'
gem 'mysql2'
gem 'omniauth'
gem 'omniauth-linkedin'
gem 'simple_form'
group :development do
  gem 'better_errors'
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'html2haml'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
  gem 'rubocop'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
